version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    environment:
      - RAILS_DB_URL_DEV=postgresql://postgres:password@db/APP_NAME_development
      - RAILS_DB_URL_TEST=postgresql://postgres:password@db/APP_NAME_test
    build: .
    command: /bin/sh -c "rm -f /APP_NAME/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/APP_NAME
      - /APP_NAME/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
